### ISSUE TITLE
mark skipped tests as No-Defect type

### ISSUE THREAD

**Issue by YBB8201** [reportportal/example-net-nunit#12]
Hi

can I use the following code in order to mark skipped tests as No-Defect type ?
https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs

I have version 5.3.4. do i need to upgrade to 5.5 ?

**Comment by nvborisenko** [comment]
Yes,

```csharp
            // don't assign "To investigate" for skipped tests
            if (e.FinishTestItemRequest.Status == Status.Skipped)
            {
                e.FinishTestItemRequest.Issue = new Issue
                {
                    Type = WellKnownIssueType.NotDefect
                };
            }
```

This is going to be separate extension, which will work for all agents, not only for nunit. When extension will be released, just install it without coding.

**Comment by YBB8201** [comment]
I have version 5.3.4 - I added it to my constructor or my report portal handler class, but it didn't work.
when you say "This is going to be separate extension, which will work for all agents, not only for nunit. When extension will be released, just install it without coding." - do you mean it will be available in the future (not now?)

**Comment by nvborisenko** [comment]
in the future

**Comment by YBB8201** [comment]
when do you think it will be available ?

**Comment by nvborisenko** [comment]
When personal time allows.

**Comment by nvborisenko** [comment]
Resolved by https://github.com/nvborisenko/reportportal-extensions-skippable extension
