### ISSUE TITLE
How to use Bridge.LogMessage from Test

### ISSUE THREAD

**Issue by lpaslavskaya** [reportportal/example-net-nunit#2]
In "example-net-nunit" project when using  Bridge.LogMessage directly from the Test, messages are not present in ReportPortal in "Error" "Debug" "Warn" "Trace" log levels.
Are any examples how to use Bridge.LogMessage directly from the test?

Example of Test method:

[Category("T1")]
[Test]
public void Test1()
{
            Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Trace, "class1 test1 log message - Trace");
            Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Debug, "class1 test1 log message - Debug");
            Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Error, "class1 test1 log message - Error");
            Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Info, "class1 test1 log message - Info");
            Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.Warning, "class1 test1 log message - Warning");
            Bridge.LogMessage(ReportPortal.Client.Models.LogLevel.None, "class1 test1 log message - None");
}

**Comment by nvborisenko** [comment]
Thanks for the question. This is known issue in the current implementation, and this is why we are still in the beta status.

If you really need supporting of log levels you can update packages to the latest beta and try to use something like:
```
Bridge.Context.LaunchReporter.LastTestNode.Log(new LogRequest{Level = Levels.Debug, Message = "my message", Time = DateTime.UtcNow})
```
This way will face the issue with parallel tests execution, and this piece of code will changed after package's release.

**Comment by lpaslavskaya** [comment]
Upgrade to ReportPortal NUnit Version 3.1.0-beta-8 didn't help.
During test execution Bridge.Context.LaunchReporter and Bridge.Service are null as it was in original version of Report Portal from example.
Do we need additional configuration steps for "example-net-nunit" solution to have Bridge.Context correctly initialized and set up in context of Test methods?

Basically I need to attach screenshot to Attachment tab in the Report Portal
![image](https://user-images.githubusercontent.com/29304599/27123754-855bb574-50f7-11e7-9c1c-ed711f91f19a.png)

I took the solution, advised here https://github.com/reportportal/logger-net-nlog/issues/1
So, example of Test method will look like:

[Category("T1")]
[Test]
public void Test1()
{
var image = ScreenshotCapture.TakeScreenshot(true);
var imageConverter = new ImageConverter();
Bridge.Context.LaunchReporter.LastTestNode.Log(new AddLogItemRequest
{
   Level = ReportPortal.Client.Models.LogLevel.Info,
   Text = "my message",
   Time = DateTime.UtcNow,
   Attach = new Attach("Screenshot", "image/png", (byte[])imageConverter.ConvertTo(image, typeof(byte[])))
});
//Some test actions
}

**Comment by nvborisenko** [comment]
The easiest way is to execute your tests with `--inprocess` parameter for nunit-console.exe. In this case `Bridge.Context` should not be null in your tests.

**Comment by andrewyakonyuk** [comment]
It doesn't work. Setup the parameter `--inprocess` didn't help and `Bridge.Service` is still null. Any ideas? Thanks.

**Comment by nvborisenko** [comment]
The original issue is resolved in release version of ReportPortal.NUnit package. Just use `Bridge.LogMessage`, this woks with parallel tests as well.

If you have any others issues, please create new one.
