### ISSUE TITLE
Cannot seem to attach images to reportportal 

### ISSUE THREAD

**Issue by nabsofken** [reportportal/example-net-nunit#3]
I am trying to attach a screenshot using the code below but I always get a null reference exception. Am I missing something?
I am using NUnit Console Runner 3.6.1 to run my tests.
ReportPortal.Client version 1.2.8
ReportPortal.NUnit version 3.2.3
ReportPortal.Shared version 1.4.2
OS: MAC OSX 10.12.5

>  Bridge.Context.LaunchReporter.LastTestNode.Log(new AddLogItemRequest
					{
						Level = LogLevel.Info,
						Text = "Screenshot",
						Time = DateTime.UtcNow,
                        Attach = new Attach("Screenshot", 
                                            "image/png", 
                                            (byte[])imageConverter
                                            .ConvertTo(Image.FromFile(Path.Combine(file.Trim(), info.ScenarioInfo.Title.Replace(" ", "_")+".png")), typeof(byte[])))
					});

`System.NullReferenceException: Object reference not set to an instance of an object`

**Comment by nvborisenko** [comment]
This code works if you execute your tests with `--inprocess` parameter. Please don't do it.

The better way to use log formatters:
```
var filePath = TestContext.CurrentContext.TestDirectory + "/dog.png";
Bridge.LogMessage(LogLevel.Info, "my dog {rp#file#" + filePath + "}");
```

This way will work even if you execute tests in parallel. Sorry for pure documentation.

**Comment by nabsofken** [comment]
Thank you so much @nvborisenko  it worked
