### ISSUE TITLE
Attachments not added to test

### ISSUE THREAD

**Issue by stoyankolev** [reportportal/example-net-nunit#7]
I have read all the closed related issues, but I am unable to add attachment to test using the example code.

Here is my code:
        public void Screenshot(byte[] bytes)
        {
            string path = Path.GetTempFileName();
            File.WriteAllBytes(path, bytes);
            ReportPortal.Shared.Log.Info("screenshot {rp#file#" + path + "}");
            Bridge.LogMessage(LogLevel.Info, "screenshot {rp#file#" + path + "}");
        }

I tried both log methods, but still no attachment was present after test execution.

The project is using .NET core, the tests are run with "dotnet test" command. Dependencies: ReportPortal.Specflow.2.1.3 and ReportPortal.Serilog.1.0.4. I can see the test executed, the results and the logs, but not attachments.

**Comment by nvborisenko** [comment]
If you write
```csharp
ReportPortal.Shared.Log.Info("some message");
ReportPortal.Shared.Log.Info("screenshot {rp#file#" + path + "}");
```

you see `some message` on RP, but not screenshot?

**Comment by stoyankolev** [comment]
OK, what I was doing, was creating a temp file from the screenshot, then the log messages, and then I deleted the temp file. 
I have commented now in my code the deletion of the temp file, and it is successfully uploaded in the results. Maybe the deletion was too soon after the log message?
I don't want to leave temp files on the location my runner is running, how can I upload the file as byte array directly, or how can I know when the file is uploaded and is ready to be deleted?

**Comment by nvborisenko** [comment]
Right, sending data via pattern `{rp#some#file}` works as deferred because of the reporting is proceeded in background thread.

New versions of "ReportPortal.Shared" package bring new possibilities to send data directly to the server:
```csharp
public static void Info(string message, string mimeType, byte[] content)
```

Try it
```
ReportPortal.Shared.Log.Info("my screenshot", "image/png", my_bytes)
```

**Comment by stoyankolev** [comment]
I have updated to the new version and using this method is working great. I attach the byte array directly, instead of creating temp files. Thank you!
