### ISSUE TITLE
Connect loggs with ReSharper

### ISSUE THREAD

**Issue by valsoray14** [reportportal/example-net-nunit#9]
What should I use instead of interface IBridgeExtension in last version of RP? If I need to use ILogHandler than how can I connect my extension class and Bridge?

**Comment by nvborisenko** [comment]
Please help me and remind how you used `IBridgeExtension`. What I know, this generic interface was divided into 2: `ILogHandler` and `ILogFormatter`.
Handler - you handle all incoming log messages from tests and you know what to do with it, so reporter believes you.
Formatter - just modify log message in real-time.

**Comment by valsoray14** [comment]
Thanks for quick reply.
I used code in old version of RP like following:
```
public class BridgeExtension : IBridgeExtension
    {
        public bool Handled { get; set; }

        public int Order => int.MaxValue;

        public void FormatLog(ref AddLogItemRequest logRequest)
        {
            NUnit.Framework.TestContext.Progress.WriteLine(logRequest.Text);
            Handled = true;
        }
    }
```

It worked for me with Bridge.LogMessage(...). I had loggs in console and ReSharper. How can I adjust such behavior with two new interfaces? All my attempts were unsuccessful

**Comment by nvborisenko** [comment]
Extensions are introduced especially for reporting only, it should not affect your code. What code in tests you use to produce log messages? Any log frameworks like serilog, log4net, nlog?

`Bridge.LogMessage()` is going to be replaced with `Log.Info()`.

**Comment by valsoray14** [comment]
I don`t use any log framework or appenders. I just use Bridge.LogMessage(LogLevel.Info, message) and implement ILogFormatter instead of IBridgeExtensions. Also, I tried to use Log class, it did not help. I had loggs only on RP and did not have them in ReSharper

**Comment by nvborisenko** [comment]
To archive your goal:
- implement ILogHandler
- set Order of your extension to 10
- return false in your Handle method

**Comment by nvborisenko** [comment]
@valsoray14 did it help?

**Comment by nvborisenko** [comment]
Closing, feel free to reopen.
